---
# tasks file for ansible-pacemaker
- include: debian.yml
  when: ansible_os_family == "Debian"
  
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: config.yml
  tags:
    - pacemaker_config

- include: cluster.yml
  tags:
    - pacemaker_cluster
