---
# handlers file for ansible-pacemaker
- name: pacemaker commit
  pacemaker: commit

- name: restart corosync
  service:
    name: corosync
    state: restarted

- name: restart pacemaker
  service:
    name: pacemaker
    sleep: 10
    state: restarted
